//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarberBoss.Domain.Reports {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceReportGenerationMessages_pt_BR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceReportGenerationMessages_pt_BR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BarberBoss.Domain.Reports.ResourceReportGenerationMessages.pt-BR", typeof(ResourceReportGenerationMessages_pt_BR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor.
        /// </summary>
        internal static string AMOUNT {
            get {
                return ResourceManager.GetString("AMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do barbeiro.
        /// </summary>
        internal static string BARBER_NAME {
            get {
                return ResourceManager.GetString("BARBER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faturamento para.
        /// </summary>
        internal static string BILLINGS_FOR {
            get {
                return ResourceManager.GetString("BILLINGS_FOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do cliente.
        /// </summary>
        internal static string CLIENT_NAME {
            get {
                return ResourceManager.GetString("CLIENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string DATE {
            get {
                return ResourceManager.GetString("DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observações.
        /// </summary>
        internal static string NOTES {
            get {
                return ResourceManager.GetString("NOTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Método de pagamento.
        /// </summary>
        internal static string PAYMENT_METHOD {
            get {
                return ResourceManager.GetString("PAYMENT_METHOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dinheiro.
        /// </summary>
        internal static string PAYMENT_METHOD_CASH {
            get {
                return ResourceManager.GetString("PAYMENT_METHOD_CASH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cartão de crédito.
        /// </summary>
        internal static string PAYMENT_METHOD_CREDIT_CARD {
            get {
                return ResourceManager.GetString("PAYMENT_METHOD_CREDIT_CARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cartão de débito.
        /// </summary>
        internal static string PAYMENT_METHOD_DEBIT_CARD {
            get {
                return ResourceManager.GetString("PAYMENT_METHOD_DEBIT_CARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pix.
        /// </summary>
        internal static string PAYMENT_METHOD_ELECTRONIC_TRANSFER {
            get {
                return ResourceManager.GetString("PAYMENT_METHOD_ELECTRONIC_TRANSFER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outro.
        /// </summary>
        internal static string PAYMENT_METHOD_OTHER {
            get {
                return ResourceManager.GetString("PAYMENT_METHOD_OTHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serviço.
        /// </summary>
        internal static string SERVICE_NAME {
            get {
                return ResourceManager.GetString("SERVICE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Situação.
        /// </summary>
        internal static string STATUS {
            get {
                return ResourceManager.GetString("STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelado.
        /// </summary>
        internal static string STATUS_CANCELLED {
            get {
                return ResourceManager.GetString("STATUS_CANCELLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pago.
        /// </summary>
        internal static string STATUS_PAID {
            get {
                return ResourceManager.GetString("STATUS_PAID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total do faturamento.
        /// </summary>
        internal static string TOTAL_BILLINGS_ON {
            get {
                return ResourceManager.GetString("TOTAL_BILLINGS_ON", resourceCulture);
            }
        }
    }
}
